// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrDvRyijL9FbX2emLrAuQyDpMJ3EBRdwI',
    appId: '1:389644661500:web:0e97e21e0c6af977839d79',
    messagingSenderId: '389644661500',
    projectId: 'gymapp-7aebd',
    authDomain: 'gymapp-7aebd.firebaseapp.com',
    storageBucket: 'gymapp-7aebd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA64-qDuA4u5T862YqOb2IpRJV4TyzZXVE',
    appId: '1:389644661500:android:332b253c5f3f844e839d79',
    messagingSenderId: '389644661500',
    projectId: 'gymapp-7aebd',
    storageBucket: 'gymapp-7aebd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTEfFLWRJcMoH7VTb0ScJImAjAjfQLwIk',
    appId: '1:389644661500:ios:b788f46cab9b4588839d79',
    messagingSenderId: '389644661500',
    projectId: 'gymapp-7aebd',
    storageBucket: 'gymapp-7aebd.appspot.com',
    iosClientId: '389644661500-vrlc8tnkfdrf4qnji68n330ole8m6bs9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTEfFLWRJcMoH7VTb0ScJImAjAjfQLwIk',
    appId: '1:389644661500:ios:b788f46cab9b4588839d79',
    messagingSenderId: '389644661500',
    projectId: 'gymapp-7aebd',
    storageBucket: 'gymapp-7aebd.appspot.com',
    iosClientId: '389644661500-vrlc8tnkfdrf4qnji68n330ole8m6bs9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymApp',
  );
}
